// <auto-generated />
using System;
using MachOps.Migrations.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachOps.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250816142049_InitialDeploy")]
    partial class InitialDeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachOps.Domain.Entities.Machinery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("MachOps.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MachOps.Domain.Entities.Machinery", b =>
                {
                    b.OwnsOne("MachOps.Domain.ValueObjects.Generics.CreatedAt", "CreatedAt", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("Datetime")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Generics.LastUpdatedAt", "LastUpdatedAt", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("DateTime2")
                                .HasColumnName("LastUpdatedAt");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.Description", "Description", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.Location", "Location", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .HasColumnType("Nvarchar(20)")
                                .HasColumnName("Location");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.MachType", "MachType", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("Type");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.MaintenanceReturn", "MaintenanceReturn", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("Date")
                                .HasColumnName("Return");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.MaintenanceStart", "MaintenanceStart", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("Date")
                                .HasColumnName("Start");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.Name", "Name", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(30)")
                                .HasColumnName("Name");

                            b1.HasKey("MachineryId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Name_Machines")
                                .IsUnique();

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Machinery.Status", "Status", b1 =>
                        {
                            b1.Property<int>("MachineryId")
                                .HasColumnType("Int");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("Status");

                            b1.HasKey("MachineryId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineryId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("LastUpdatedAt")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("MachType")
                        .IsRequired();

                    b.Navigation("MaintenanceReturn")
                        .IsRequired();

                    b.Navigation("MaintenanceStart")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("MachOps.Domain.Entities.UserAccount", b =>
                {
                    b.OwnsOne("MachOps.Domain.ValueObjects.Generics.CreatedAt", "CreatedAt", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("SmallDateTime")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.Generics.Active", "Active", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<bool>("Value")
                                .HasColumnType("Bit")
                                .HasColumnName("Active");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.UserAccount.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Email_Users")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.UserAccount.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.UserAccount.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Password");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.UserAccount.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Phone_Users")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("MachOps.Domain.ValueObjects.UserAccount.Role", "Role", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("Role");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Active")
                        .IsRequired();

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
